#!/usr/bin/env bash

LDFlags :=
ifeq ($(OS),Windows_NT)
else
	UNAME_S := $(shell uname -s)
	ifeq ($(UNAME_S),Linux)
		CPFlags += -Lr
		LDFlags += -ldflags="-linkmode external -extldflags -static -s -w"
	endif
	ifeq ($(UNAME_S),Darwin)
		CPFlags += -r
	endif
endif

GOOS=linux GOARCH=amd64 go build $(LDFlags) -tags netgo --installsuffix netgo "$@"
