#!/usr/bin/env bash

export LDFlags=""
export LDFlagPrefix=""
if [[ "$OS" != "Windows_NT" ]]; then
	UNAME_S=$(uname -s)
	if [[ "$UNAME_S" == "Linux" ]]; then
	  LDFlagPrefix=-ldflags=
		LDFlags="-linkmode external -extldflags -static -s -w"
	fi
fi
echo "Building with flags: $LDFlags"

GOOS=linux GOARCH=amd64 go build $LDFlagPrefix"$LDFlags" -tags netgo --installsuffix netgo "$@"
