#!/usr/bin/env bash

export LDFlags=""
if [[ "$OS" == "Windows_NT" ]]; then
	UNAME_S=$(shell uname -s)
	if [[ "$UNAME_S" == "Linux" ]]; then
		LDFlags=-ldflags="-linkmode external -extldflags -static -s -w"
	fi
fi

GOOS=linux GOARCH=amd64 go build $LDFlags -tags netgo --installsuffix netgo "$@"
